insert into public.categories (
  name_ar,
  name_en,
  slug,
  description_ar,
  sort_order,
  is_active,
  is_featured
) values
  ('العود', 'Oud', 'oud', 'دهن عود وقطع مختارة بطابع خشبي عميق.', 1, true, true),
  ('البخور', 'Bakhoor', 'bakhoor', 'بخور فاخر للبيت والضيافة اليومية.', 2, true, true),
  ('العطور', 'Perfumes', 'perfumes', 'عطور عربية وشرقية للاستخدام اليومي والخاص.', 3, true, true),
  ('المسك', 'Musk', 'musk', 'مسك ناعم ونظيف بثبات هادئ.', 4, true, false),
  ('أطقم الهدايا', 'Gift Sets', 'gift-sets', 'مجموعات جاهزة للإهداء بتغليف راق.', 5, true, true)
on conflict (slug) do update set
  name_ar = excluded.name_ar,
  name_en = excluded.name_en,
  description_ar = excluded.description_ar,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_featured = excluded.is_featured;

insert into public.store_settings (
  store_name_ar,
  store_name_en,
  contact_phone,
  whatsapp_number,
  support_email,
  instagram_url,
  delivery_fee_omr,
  free_delivery_threshold_omr,
  default_currency,
  is_store_open,
  brand_story_ar,
  delivery_policy_ar,
  returns_policy_ar,
  privacy_policy_ar,
  terms_ar,
  default_meta_title_ar,
  default_meta_description_ar
)
select
  'عود ياز',
  'Oud Yaz',
  '+96890000000',
  '+96890000000',
  'support@oudyaz.example',
  'https://instagram.com/oudyaz',
  2.000,
  30.000,
  'OMR',
  true,
  'عود ياز متجر عربي فاخر للعود والبخور والعطور والمسك وأطقم الهدايا.',
  'التوصيل داخل عمان حسب المناطق المتاحة، وسيتم تأكيد التفاصيل قبل تجهيز الطلب.',
  'يتم التعامل مع الاسترجاع والاستبدال وفق حالة المنتج وسياسة المتجر.',
  'نحترم خصوصية العملاء ونستخدم البيانات لغرض معالجة الطلبات فقط.',
  'باستخدام المتجر فإنك توافق على شروط البيع والتوصيل وسياسات المتجر.',
  'عود ياز | عود وبخور وعطور فاخرة',
  'متجر عربي فاخر للعود والبخور والعطور والمسك وأطقم الهدايا في عمان والخليج.'
where not exists (select 1 from public.store_settings);

insert into public.products (
  category_id,
  name_ar,
  name_en,
  slug,
  short_description_ar,
  description_ar,
  price_omr,
  compare_at_price_omr,
  sku,
  stock_quantity,
  low_stock_threshold,
  is_active,
  is_featured,
  is_best_seller,
  is_new_arrival,
  scent_family,
  intensity,
  size_label,
  usage_ar,
  occasion_ar,
  meta_title_ar,
  meta_description_ar,
  search_keywords_ar,
  weight_grams,
  volume_ml,
  burn_time,
  sort_order
) values
  (
    (select id from public.categories where slug = 'oud'),
    'دهن عود ملكي',
    'Royal Oud Oil',
    'royal-oud-oil',
    'دهن عود عميق بطابع خشبي ودخاني راق.',
    'اختيار فاخر لمحبي العود الشرقي العميق، مناسب للمجالس والمناسبات الخاصة والإهداء الرسمي.',
    28.000,
    34.000,
    'OY-OUD-001',
    12,
    5,
    true,
    true,
    true,
    false,
    'خشبي، دخاني، دافئ',
    'قوي',
    '12 مل',
    'توضع كمية خفيفة على نقاط النبض.',
    'المجالس، المناسبات، الهدايا',
    'دهن عود ملكي | عود ياز',
    'دهن عود فاخر بطابع خشبي ودخاني مناسب للهدايا والمناسبات.',
    'عود، دهن عود، عود ملكي، هدية',
    80,
    12.00,
    null,
    1
  ),
  (
    (select id from public.categories where slug = 'bakhoor'),
    'بخور المساء الخليجي',
    'GCC Evening Bakhoor',
    'gcc-evening-bakhoor',
    'بخور دافئ يترك أثراً ناعماً في المكان.',
    'رائحة مناسبة للمساء والضيافة، تجمع بين الدفء العربي ولمسة هادئة لا تطغى على المكان.',
    12.500,
    null,
    'OY-BKH-002',
    18,
    6,
    true,
    true,
    false,
    false,
    'عنبر، خشب، حلاوة خفيفة',
    'متوسط',
    '50 جم',
    'يوضع على مبخرة ساخنة بكمية مناسبة.',
    'الضيافة، البيت، الزيارات',
    'بخور المساء الخليجي | عود ياز',
    'بخور دافئ وفاخر مناسب للبيت والضيافة اليومية.',
    'بخور، بخور خليجي، ضيافة، البيت',
    50,
    null,
    '45 دقيقة تقريباً',
    2
  ),
  (
    (select id from public.categories where slug = 'perfumes'),
    'عطر ياز الشرقي',
    'Yaz Oriental Perfume',
    'yaz-oriental-perfume',
    'عطر شرقي بتوازن بين الفخامة والهدوء.',
    'تركيبة أنيقة للاستخدام اليومي والخاص، تمنح حضوراً عربياً واضحاً دون مبالغة.',
    19.750,
    null,
    'OY-PER-003',
    3,
    5,
    true,
    false,
    true,
    true,
    'زهري، مسك، خشب',
    'متوسط',
    '100 مل',
    'يرش على الملابس من مسافة مناسبة ويحفظ بعيداً عن الحرارة.',
    'اليوميات، العمل، المناسبات',
    'عطر ياز الشرقي | عود ياز',
    'عطر شرقي فاخر للاستخدام اليومي والخاص.',
    'عطر، عطر شرقي، مسك، خشب',
    260,
    100.00,
    null,
    3
  )
on conflict (slug) do update set
  category_id = excluded.category_id,
  name_ar = excluded.name_ar,
  name_en = excluded.name_en,
  short_description_ar = excluded.short_description_ar,
  description_ar = excluded.description_ar,
  price_omr = excluded.price_omr,
  compare_at_price_omr = excluded.compare_at_price_omr,
  sku = excluded.sku,
  stock_quantity = excluded.stock_quantity,
  low_stock_threshold = excluded.low_stock_threshold,
  is_active = excluded.is_active,
  is_featured = excluded.is_featured,
  is_best_seller = excluded.is_best_seller,
  is_new_arrival = excluded.is_new_arrival,
  scent_family = excluded.scent_family,
  intensity = excluded.intensity,
  size_label = excluded.size_label,
  usage_ar = excluded.usage_ar,
  occasion_ar = excluded.occasion_ar,
  meta_title_ar = excluded.meta_title_ar,
  meta_description_ar = excluded.meta_description_ar,
  search_keywords_ar = excluded.search_keywords_ar,
  weight_grams = excluded.weight_grams,
  volume_ml = excluded.volume_ml,
  burn_time = excluded.burn_time,
  sort_order = excluded.sort_order;

insert into public.banners (
  title_ar,
  title_en,
  subtitle_ar,
  image_url,
  mobile_image_url,
  link_url,
  button_label_ar,
  placement,
  sort_order,
  is_active
)
select
  'فخامة العود بروح عربية',
  'Luxury Oud With Arabic Soul',
  'مختارات راقية من العود والبخور والعطور لأهل الذوق.',
  'https://placehold.co/1600x900/361f14/b88945?text=Oud+Yaz',
  'https://placehold.co/900x1200/361f14/b88945?text=Oud+Yaz',
  '/products',
  'تسوق الآن',
  'home_hero',
  1,
  true
where not exists (
  select 1
  from public.banners
  where placement = 'home_hero'
    and sort_order = 1
);
