const auditActionLabels: Record<string, string> = {
  "admin.login": "تسجيل دخول",
  "admin.logout": "تسجيل خروج",
  "admin.create": "إضافة إداري",
  "admin.update": "تعديل إداري",
  "admin.delete": "حذف إداري",
  "admin.disable": "تعطيل إداري",
  "admin.enable": "تفعيل إداري",
  "admin.password_reset_requested": "طلب إعادة تعيين كلمة المرور",
  "order.status_change": "تغيير حالة طلب",
  "order.cancel": "إلغاء طلب",
  "order.complete": "إكمال طلب",
  "order.assigned": "تعيين مسؤول الطلب",
  "order.unassigned": "إلغاء تعيين مسؤول الطلب",
  "order.note_added": "إضافة ملاحظة داخلية",
  "order.note_updated": "تعديل ملاحظة داخلية",
  "order.note_deleted": "حذف ملاحظة داخلية",
  "note.delete": "حذف ملاحظة داخلية",
  "order.invoice_printed": "طباعة الفاتورة",
  "order.shipping_label_printed": "طباعة بوليصة الشحن",
  "invoice.create": "إنشاء فاتورة",
  "invoice.print": "طباعة فاتورة",
  "invoice.print_a4": "طباعة فاتورة A4",
  "invoice.print_thermal_80": "طباعة إيصال حراري 80 ملم",
  "invoice.print_thermal_58": "طباعة إيصال حراري 58 ملم",
  "invoice.download": "تحميل PDF فاتورة",
  "return.approve": "اعتماد مرتجع",
  "return.reject": "رفض مرتجع",
  "return.receive": "استلام مرتجع",
  "return.close": "إغلاق مرتجع",
  "refund.create": "تسجيل استرداد",
  "refund.delivery_fee_included": "تم تضمين رسوم التوصيل في الاسترداد",
  "banner.delete": "حذف بنر",
  "product.delete": "حذف منتج",
  "product.disable": "تعطيل منتج",
  "category.delete": "حذف تصنيف",
  "category.disable": "تعطيل تصنيف",
  "coupon.delete": "حذف كوبون",
  "coupon.disable": "تعطيل كوبون",
  "coupon.enable": "تفعيل كوبون",
  "occasion.delete": "حذف مناسبة",
  "customer.delete_test": "حذف عميل تجريبي"
};

export function getAuditActionLabel(action: string) {
  return auditActionLabels[action] ?? action;
}
